name: Changelog CI

on:
  pull_request:
    branchss: main
    types: [ opened, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Check state
        run: ls -la

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.rst
          config_file: ./configs/changelog-ci-config.json
          github_token: ${{ secrets.GITHUB_TOKEN }}
