name: Make Coverage Badge
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: action-badges/create-orphan-branch@0.1.0
        with:
          branch-name: main

      - name: Make Coverage Badge
        uses: action-badges/cobertura-coverage-xml-badges@0.2.1
        with:
          file-name: coverage.svg
          badge-branch: main
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          coverage-file-name: ./coverage.xml
